arch: s390x
services:
  - docker
env:
  global:
    - TEST_DIR="$PWD/9.0/fpm-alpine3.12/"
    - TEST_SCRIPT="test.sh"
    - BUILD_DIR="$PWD/9.0/fpm-alpine3.12/"
    - REPO="quay.io/ibmz/drupal-s390x"
    - TAG="$REPO:9.0"
before_script: 
  - cd $BUILD_DIR && chmod +x *
  - cd $TEST_DIR && chmod +x $TEST_SCRIPT
  - docker login quay.io -u $ROBOT_USER -p $ROBOTTOKEN
script: 
  - docker build $BUILD_DIR --tag $TAG
  - cd $TEST_DIR && bash $TEST_SCRIPT 
after_script:
  - docker push $TAG
